# Generated by Django 5.0.1 on 2024-02-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genre_remove_book_genre_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_path',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='text_path',
            field=models.FileField(default='default_text.txt', upload_to='texts/'),
        ),
    ]
