# Generated by Django 5.0.1 on 2024-02-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_book_image_path_book_text_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_path',
            field=models.ImageField(default='default_image.jpg', upload_to='books/images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_path',
            field=models.FileField(default='default_text.txt', upload_to='books/texts/'),
        ),
    ]
