# Generated by Django 5.0.1 on 2024-02-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_chapter_chapter_number_alter_chapter_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
