# Generated by Django 5.0.1 on 2024-03-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_book_author_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='id',
        ),
    ]
