# Generated by Django 5.0.1 on 2024-06-07 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField()),
                ('book_cover', models.ImageField(upload_to='book_covers/')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('views', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.genre')),
            ],
        ),
    ]
